"""empty message

Revision ID: afb1a4c1a371
Revises: c9e2ce014fac
Create Date: 2023-08-26 16:07:33.263062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afb1a4c1a371'
down_revision = 'c9e2ce014fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('description', sa.String(), nullable=True)) #Automatic created

        batch_op.add_column("invoices", sa.Column("enable_downloads", sa.Boolean(), nullable=True,default=False),)
        batch_op.execute("UPDATE invoices SET enable_downloads = False")


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        #batch_op.drop_column('description') #Automatic created

        batch_op.drop_column("invoices","enable_downloads") 


    # ### end Alembic commands ###
